### ISSUE TITLE
Перевод названия «Free as in Freedom»

### ISSUE THREAD

**Issue by jollheef** [jollheef/free-as-in-freedom-v2-ru#11]
В русском языке есть «свободный» и «бесплатный», поэтому изначальная игра слов из названия теряет смысл при переводе.

**Comment by yurytch** [comment]
И не надо играть. Это биография, названная по западным образцам -- образ и объяснение.
Предлагаю не обезьянничать с формой и назвать: "Свободные программы: Ричард Столлман и его революция. Выпуск 2".

**Comment by vazhnov** [comment]
Как вариант, можно не переводить название, а оставить его как есть.

**Comment by jollheef** [comment]
@yurytch, текущее название книги — это перевод не оригинального названия, а того, что придумал RMS на замену. 

Я его спросил, каким образом он бы назвал книгу в том случае, если бы в английском языке были бы разные слова для free as in freedom и free as in free beer, и он предложил использовать «Liberating your computer».

**Comment by yurytch** [comment]
Спорно, потому что: 1) название книги придумал Вильямс, и вопрос Столлману вообще был ни к чему; 2) игра слов, как правило, не переводится вовсе; 3) last but not least - это плохое название, потому что попросту не о том - смысл утерян. 
(на всякий пожарный - если название Вильямсу придумал Столлман, то всё равно вопрос был сформулирован некорректно)

**Comment by jollheef** [comment]
Вопрос (который я считаю корректным) все равно будет к RMS, так как спрашивать больше некого (публичных контактов Sam Williams я не нашел), да и книга о нем самом ― он имеет полное право.

В 2f9757ae35b8bbdfa0ff0ad8ef67f2bf1503136b я попробовал убрать левую часть, далее посмотрим на отклик сообщества и мнение самого RMS. Переоткрываю эту задачу до его положительного ответа.

**Comment by yurytch** [comment]
Обычная практика в таких случаях (нет контактов) -- действовать через издательство? Вильямс печатался в ОР и в Рандом Хаус.
А у Столлмана вы будете спрашивать, фактически, как переводить на русский. Что как бы не его ответственность. Ну не переводят игру слов, тем более в названиях )))
Но сейчас, по крайней мере, это выглядит приемлемо. Только добавьте где-нибудь, что это вторая редакция.

**Comment by jollheef** [comment]
> Ну не переводят игру слов, тем более в названиях )))

Я не знаю с чего вы решили, что кто-то переводил игру слов. Вы уже дважды пишете о о том, чем никто и не пытался заниматься.

В отсутствие исходного смысла было предложено сменить название. Я вижу это хорошим решением.

**Comment by yurytch** [comment]
> > Ну не переводят игру слов, тем более в названиях )))
> 
> Я не знаю с чего вы решили, что кто-то переводил игру слов. Вы уже дважды пишете о о том, чем никто и не пытался заниматься.

Ваш собственный комментарий, 1-й здесь, и описание вопроса Столлману ("что бы подобрать близкое по смыслу к 1-й части названия"). 
....короче, посмотрите, как решало похожие проблемы с названиями издательство "Мир".

**Comment by jollheef** [comment]
> Ваш собственный комментарий, 1-й здесь, и описание вопроса Столлману ("что бы подобрать близкое по смыслу к 1-й части названия").

Ваша цитата в кавычках ― это ваши слова, а не мои. Ничего подобного я не писал.

**Comment by yurytch** [comment]
> > Ваш собственный комментарий, 1-й здесь, и описание вопроса Столлману ("что бы подобрать близкое по смыслу к 1-й части названия").
> 
> Ваша цитата в кавычках ― это ваши слова, а не мои. Ничего подобного я не писал.

Ваш комментарий от 6.8.19, 09:59. Верно, вторую часть фразы я оформил нечётко, но существенной утраты смысла не было. Вы спрашивали, как бы Столлман (а не автор книги Вильямс!) заменил английскую игру слов. Зачем??? 

Вот ещё кое-что (ткнул пальцем на прощание))) ):

Continuing the fight - не "битва", а "борьба"
вместо "свободный софт" лучше говорить "свободные программы" или "программное обеспечение"
корпократия - корпорократия
антиутопический - мрачно-футуристический

с.179 (в английском p.186)
"**Столлману 48 лет**, и он ещё вполне..."
"внушительный" там нет
не "импульс" а "сила" или "популярность движения"; импульс в отношении людей это побуждение, порыв
не "вне битв" (???), а "за рамками" 
"august" не "суровый", а "величественный" или "масштабный" (здесь, возможно, употреблено полуиронично)
"picking his fights..." -- "ввязываясь в битвы (сражения, бои)", а не "за себя" -- имеется в виду, что он ввязывался "не в те бои" и потерял поддержку людей, которые могли бы стать ему великими (или могучими...) соратниками (champions), а "не стать великими" (??!) -- если бы, мол, тот воевал "не за свои, а за их взгляды" (кстати, интересное место )) ).
"Это тоже свидетельство..." -- "**Но** [противопоставление] то, что многие из давних (!) политических противников готовы сказать добрые слова о нём, свидетельствует о его прямом и принципиальном характере".
"напряжённая противоречивость" (?) -- "раздор" (или "разногласия")

Короче, друзья, советую 0.99 убрать и честно назвать очень дальним черновиком.

**Comment by jollheef** [comment]
Удалил нерелевантные к задаче комментарии. Пожалуйста, воздержитесь от желания самоутверждаться при нахождении каждой значительной или не очень ошибки. Цель данного репозитория ― в совместном улучшении перевода.

**Comment by jollheef** [comment]
RMS одобрил вариант «Richard Stallman and the Free Software Revolution», так что книга на русском будет называться «Ричард Столлман и революция свободного программного обеспечения».
