### ISSUE TITLE
faif-2.0.pdf скачивается а не открывается в браузере

### ISSUE THREAD

**Issue by 532910** [jollheef/free-as-in-freedom-v2-ru#13]
Ссылка https://github.com/jollheef/free-as-in-freedom-v2-ru/releases/download/v0.99/faif-2.0.pdf молча скачивается, в то время как все нормальные pdf открываются в браузере.

**Comment by vchimishuk** [comment]
OS, browser, version?

**Comment by mandala-mbwa** [comment]
FreeBSD 11.3, firefox 68.0, amd64 - выдает запрос действия "Открыть в программе/сохранить", запоминание действия деактивировано. При этом рандомный PDF по любой сылке из гугла нормально открывается сразу в браузере, как и настроено по умолчанию.

**Comment by 532910** [comment]
debian sid, ff 68

1. [InlineDisposition Reloaded](https://addons.mozilla.org/en-US/firefox/addon/inlinedisposition-reloaded/) включен. [faif-2.0.pdf](https://github.com/jollheef/free-as-in-freedom-v2-ru/releases/download/v0.99/faif-2.0.pdf) молча скачивается.
2. [InlineDisposition Reloaded](https://addons.mozilla.org/en-US/firefox/addon/inlinedisposition-reloaded/) выключен. Появляется окошко: open with/save file. При выборе open with firefox faif-2.0.pdf сохраняется в /tmp и отрывается в новой вкладке.

Оба варианта поведения категорически неверные. Должно быть так: Файл просто открывается никуда не скачиваясь, не зависимо от того, включен InlineDisposition Reloaded или выключен. Пример: [DS_FT232R.pdf](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf)

**Comment by 532910** [comment]
В хроме всё тоже самое.

**Comment by jollheef** [comment]
Добрый день,

GitHub использует `content-disposition: attachment`, возможности изменить это нет.

**Comment by 532910** [comment]
Значит надо выкладывать в другое место. Текущее поведение --- это издевательство над пользователем. Скачай, выбери куда, открой. Крайне сложно.

**Comment by jollheef** [comment]
GitHub и не является upstream. Данный репозиторий ― зеркало для тех, кому удобно отправлять правки/получать уведомления таким способом.

**Comment by 532910** [comment]
А что является upstream?

**Comment by jollheef** [comment]
https://code.dumpstack.io/etc/free-as-in-freedom-v2-ru
