### ISSUE TITLE
перевод очень свободный

### ISSUE THREAD

**Issue by yurytch** [jollheef/free-as-in-freedom-v2-ru#17]
Смещены акценты, даже смыслы перевёрнуты кое-где (пока внимательно смотрел только предисловие). Некоторые места основного текста читаются как подстрочник.
В какой форме предлагать правки, может, патчами?

**Comment by yurytch** [comment]
Кроме того, не стоит переводить жаргон и идиомы, разумнее дать пояснения в сноске (пример - эпизод со словом "долбанутый").

**Comment by yurytch** [comment]
Не знаю толком, как работает гит, разумно ли сделать копию ("клон"?) этого репозитория и работать уже в нём? Ведь так можно автоматически изготавливать патчи?

**Comment by jollheef** [comment]
@yurytch, все предложения — патчами. 

В любом случае, если видишь ошибки перевода (а искажение — это ошибка) — стоит указать конкретные участки текста, иначе непонятно что должно быть исправлено. 

Спасибо за участие!

**Comment by yurytch** [comment]
Что, если я хочу указать желательность сноски? Пример:

--- preface-williams.tex.prev  ^2019-08-05 20:38:49.000000000 +0300
+++ preface-williams.tex       ^2019-08-06 10:39:43.193478888 +0300
@@ -146,18 +146,17 @@
 положиться лишь на записи -- довольно ненадёжный источник. Из-за
 этого я исказил формулировки Ричарда, сделав их более жёсткими.
.
-Вопросы у Столлмана возникли и к слову \enquote{долбаный}. Опять же, я не
-мог обратиться к аудиозаписи диктофона, но сказал Ричарду, что меня
-тогда впечатлила его лексика, напомнив мне о его нью-йоркских корнях,
-так что я уверен в использованном слове.
+Помимо того, у Столлмана возникли вопросы и к использованию слова \enquote{fucking} в цитате. Опять же, у меня.
+не было этого места в аудиозаписи, но я ответил, что точно помню.
+впечатляющий пример сквернословия, демонстрирующий нью-йоркские корни Ричарда,
+и в использованном слове уверен.
.
 На следующий день пришло ответное письмо, которое заставило меня
-перечитать предыдущее сообщение. Оказалось, что Столлман спорит
-не с самим словом, а с той формой, которую я использовал в книге.
+перечитать первое сообщение. Оказалось, что Столлман спорит
+не с самим словом, а с использованием его в цитате в виде прилагательного.
.
-\enquote{Сомневаюсь, что я назвал бы чью-то ошибку \enquote{долбаной}, -- писал
-мне Ричард, -- мне несвойственно так выражаться. Я бы скорее сказал:
-\enquote{долбанутая ошибка}. Поэтому я думаю, что слова искажены}.
+\enquote{Сомневаюсь и потому, что в цитате написано \enquote{долбаный}, -- писал
+мне Ричард, -- я так никогда не говорю. Поэтому думаю, что мои слова искажены}.
.
 Шах и мат.
.
И к этому требуется сноска, поясняющая, что имеется в виду именно прилагательное, и что fucking в английском это и наречие, и прилагательное.

Заодно посмотрите, как в исходном переводе уплывает смысл (здесь - появляются домыслы).
