### ISSUE TITLE
rubber хорошо бы пояснить...

### ISSUE THREAD

**Issue by yurytch** [jollheef/free-as-in-freedom-v2-ru#18]
...что это обёртка-пусковик, и дать ссылку на исходники: https://launchpad.net/rubber

**Comment by jollheef** [comment]
Доброе утро. Спасибо за предложение.

Тем не менее, я не вижу в этом особого смысла. Это же не turorial по тому, как собирать *TeX.

**Comment by yurytch** [comment]
Rubber не из состава TeX, и на ctan его нет. И он может "быть не в репе".

**Comment by jollheef** [comment]
Rubber есть во всех дистрибутивах, пользователи которых потенциально могут иметь проблемы с тем, что какая-то программа не в репе: https://repology.org/project/rubber/information.
