### ISSUE TITLE
reading from mobile devices (fb2/epub)

### ISSUE THREAD

**Issue by 532910** [jollheef/free-as-in-freedom-v2-ru#19]
Сделайте, пожалуйста, формат для чтения с мобильных экранов.

**Comment by jollheef** [comment]
Добрый день,

Внимательнее читайте [README](https://github.com/jollheef/free-as-in-freedom-v2-ru#fb2-markdown-%D0%B8%D0%BB%D0%B8-html-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8), сборка в fb2 уже описана.

**Comment by 532910** [comment]
Где ссылка скачать fb2?

**Comment by jollheef** [comment]
> Где ссылка скачать fb2?

На данный момент ― необходимо собрать самостоятельно.

**Comment by 532910** [comment]
Так вот именно об этом этот баг и есть.

**Comment by jollheef** [comment]
По ОП это было не очевидно. 

Будет решено в рамках #21. 

Спасибо.
