### ISSUE TITLE
Опечатки в тексте

### ISSUE THREAD

**Issue by dstrelnikov** [jollheef/free-as-in-freedom-v2-ru#2]
Есть ли единая точка сбора опечаток? Если нет, то можно собирать их в данном issue.

Глава 2:
-   ~~нехватает пробела: речи **Столлмана``Свободное** ПО: свобода и сотрудничество''~~

**Comment by jollheef** [comment]
Привет,

Можно через редактирование прямо на GitHub создавать pull request с исправлением.

**Comment by jollheef** [comment]
Исправлено в #5
