### ISSUE TITLE
upstream link

### ISSUE THREAD

**Issue by 532910** [jollheef/free-as-in-freedom-v2-ru#20]
Ссылка на upstream должна быть явно обозначена. Типа "этот репозиторий является копией и upstream находится тут:". А не молчаливый заголовок, который внезапно куда-то ссылается.

**Comment by jollheef** [comment]
Добрый день,

Внимательнее читайте README ― ссылка есть как в заголовке, так и в информации о сборке.

![image](https://user-images.githubusercontent.com/1749762/62529110-88d1ca00-b82d-11e9-91f1-c47fbca5cc51.png)

Не вижу смысла повторяться.
