### ISSUE TITLE
Pandoc не находит изображения при конвертации в fb2

### ISSUE THREAD

**Issue by Ilia1** [jollheef/free-as-in-freedom-v2-ru#24]
`pandoc -t fb2 faif-2.0.tex > faif-2.0.fb2`
`[WARNING] Could not fetch resource 'stignucius': PandocResourceNotFound "stignucius"`
`[WARNING] Could not fetch resource 'KL10_1979': PandocResourceNotFound "KL10_1979"`

Компиляция в другие форматы происходит без ошибок. Установлен полный комплект texlive. Ubuntu 19.04

**Comment by jollheef** [comment]
Привет,

Warning — это не ошибка, а предупреждение. 

Результат сборки есть, но он не включает в себя изображения (необходимо разобраться почему).

**Comment by Ilia1** [comment]
еще в fb2 не включаются примечания

**Comment by ghost** [comment]
Если собрать в html, тоже картинок нет

**Comment by jollheef** [comment]
> еще в fb2 не включаются примечания

Исправлено в 66fa726010787705d919d17018568cfd3261ab08.
