### ISSUE TITLE
Примечания - в подстрочник

### ISSUE THREAD

**Issue by skirpichev** [jollheef/free-as-in-freedom-v2-ru#25]
Не думаю, что нужно до такой степени следовать оригиналу, чтобы выносить примечания в конец глав.  (Да, в pdf-ке почему-то нет гиперссылок для примечаний.)

**Comment by sash-kan** [comment]
а ещё, наверно, стоит перевести сокращение ["Ibid."](https://ru.wikipedia.org/wiki/Ibid.), тринадцать раз встречающееся в примечаниях.
