### ISSUE TITLE
Оформление кавычек

### ISSUE THREAD

**Issue by dstrelnikov** [jollheef/free-as-in-freedom-v2-ru#3]
Не лучше ли оформлять кавычки через пакет [csquotes](https://ctan.org/pkg/csquotes) как `\enquote{some text}`?

Насколько я помню, он должен корректно обрабатывать вложенные кавычки.

**Comment by jollheef** [comment]
> Не лучше ли оформлять кавычки через пакет csquotes как \enquote{some text}?

C csquotes кавычки стали правильными («ёлочки»), то есть подтягивает настройки polyglossia корректно.

![image](https://user-images.githubusercontent.com/1749762/59622634-a3d36800-9121-11e9-8e00-bf146d223758.png)

А без этого можно сделать обычные кавычки — правильными? Это было бы меньшей кровью.

> Насколько я помню, он должен корректно обрабатывать вложенные кавычки.

А вот с этим как-то не получилось.

```TeX
\enquote{принтер \eqnuote{жуёт} бумагу, требуется починка}
```

```sh
$ make
rubber -m xelatex faif-2.0.tex
compiling faif-2.0.tex...
chap01.tex:37: Undefined control sequence \eqnuote.
chap01.tex:37: leading text: ... \eqnuote{жуёт} бумагу, требуется починка}
make: *** [Makefile:2: all] Error 2
```

**Comment by dstrelnikov** [comment]
> А без этого можно сделать обычные кавычки — правильными? Это было бы меньшей кровью.

"Правильными" - это елочками? `<<some text>>`

**Comment by dstrelnikov** [comment]
> \enquote{принтер \eqnuote{жуёт} бумагу, требуется починка}

Здесь у тебя просто опечатка в имени оператора.

**Comment by jollheef** [comment]
> "Правильными" - это елочками? <<some text>>

Именно!

> Здесь у тебя просто опечатка в имени оператора.

И действительно.

Да, вложенные кавычки обрабатывает корректно.

![image](https://user-images.githubusercontent.com/1749762/59648825-ea4fb380-916f-11e9-997a-2b55586c3d28.png)
