### ISSUE TITLE
также нужна сноска: под "процесс" имеется в виду процесс технологический или процедура

### ISSUE THREAD

**Issue by yurytch** [jollheef/free-as-in-freedom-v2-ru#30]
`
--- preface-williams.tex.prev.1	2019-08-05 20:38:49.000000000 +0300
+++ preface-williams.tex	2019-08-07 09:01:59.231257659 +0300
@@ -180,20 +180,16 @@
  этом можно почитать в политических заметках на моём сайте
  \url{stallman.org}.]
 
-Это весьма плачевно, потому что перед моими глазами тот самый
-XXI век, который я считал когда-то светлым будущим. Но сейчас
-его уместно назвать веком бега на месте. Я объясню, почему.
+Это печалит ещё и потому, что теперь, через десять лет, я, как мне кажется, наконец-то начал хорошо понимать XXI век. И это понимание я выразил бы словами ``век процесса''.
 
-Мы находимся в необычной точке исторического развития, где
-возможность изменить мир, невзирая на весь цинизм и пессимизм,
-действительно доступна каждому. Но в этой доступности каждому
+Я имею в виду, что мы живём в редкий момент исторического развития, когда -- отбросим пока цинизм! -- возможность изменить мир оказывается в руках каждого. Но в этой доступности каждому
 и кроется подвох. Если в прошлом можно было добиться перемен,
 завоевав расположение нескольких влиятельных фигур, то теперь
 реформатор должен придать нужное направление целому полю
 всевозможных идей, настроений и интересов самых разных людей.
 То есть, эффективный реформатор должен обладать в наше время
 титанической волей и упорством, готовностью десятилетиями
-голосить в пустыне, а также массой знаний и творческими талантами,
+вещать в пустыне, а также массой знаний и творческими талантами,
 чтобы создать идеи, способные обыграть Систему в её же игре.
 
 И Ричард Столлман подходит под все эти критерии.
`

**Comment by jollheef** [comment]
Это должно быть в pull request.
