### ISSUE TITLE
"touche" это не "шах и мат", а скорее "верно!"

### ISSUE THREAD

**Issue by yurytch** [jollheef/free-as-in-freedom-v2-ru#31]

**Comment by alexferman** [comment]
Не могу согласиться. Слово "туше" пошло из фехтования, оно означает укол противника. В той же самой борьбе оно означает контакт лопаток с полом, т.е. факт поражения. В переносном смысле оно употребляется, когда оппонент сопротивлялся в дискуссии, но ты неким убойным аргументом "уложил его на лопатки". Т.е. "шах и мат" - совершенно релевантный перевод.

**Comment by yurytch** [comment]
Ничего подобного. В нормальном англоязычном тексте это именно одно очко (т. е. как в фехтовании), но не победа. Кстати, для победы существует и образный "checkmate".

**Comment by alexferman** [comment]
Очко это и есть, так сказать, локальная победа. А в книге на этом спор закончился, так что победу Столлмана в споре можно назвать окончательной.

**Comment by yurytch** [comment]
Какое замечательная способность препираться. 
Во-первых, очко (в боксе или туше в фехтовании) это не какая-то там "локальная победа", а просто "частичный успех". 
Во-вторых, в книге нет ни спора, ни победы в нём. Столлман высказывает замечание (указывающее, что Вильямс не вполне точно понял манеру речи Столлмана), и Вильямс это тут же признаёт.

**Comment by alexferman** [comment]
Спор есть, пусть и короткий:

"Вопросы у Столлмана возникли и к слову \enquote{долбаный}. Опять же, я не
мог обратиться к аудиозаписи диктофона, но сказал Ричарду, что меня
тогда впечатлила его лексика, напомнив мне о его нью-йоркских корнях,
так что я уверен в использованном слове.

На следующий день пришло ответное письмо, которое заставило меня
перечитать предыдущее сообщение. Оказалось, что Столлман спорит
не с самим словом, а с той формой, которую я использовал в книге."

Выражения "локальная победа" и "частичный успех" идентичны по смыслу.

**Comment by alexferman** [comment]
Впрочем, у некоторых людей может быть аллергия на выражение "шах и мат!" (я тоже не переношу некоторые устоявшиеся обороты), так что можно предложить вместо него такую фразу: "И правда ведь!" или что-то в этом роде, как компромиссный вариант.

**Comment by yurytch** [comment]
"Спор" возникает лишь в вашем переводе. В книге есть вопросы/возражения Столлмана к словоупотреблению Вильямса, принимаемые немедленно.
А выражение "локальная победа" это как бы и не совсем по-русски.

**Comment by yurytch** [comment]
Короче, граждане **руководители**/**организаторы** сего проекта. 
Можете стереть и этот комментарий, но примите к сведению: перевод слабоват. А чтобы ему стать приемлемым, вам нужны не "тысяча лиц, умеющих читать по-английски", а один (ну, два) человек **с** **опытом** **перевода**, который(-е) потратит(-ят) примерно 10 человеко-часов на редактуру (около 3 минут на страницу, полагая, что все 200 страниц одинакового качества). 
И именно вы, руководители/организаторы, должны технически обеспечить этот процесс (расписав скажем, алгоритм для случая работы через гитхаб), а не предлагать людям, не в глаза не видевшим гит и дифф, "делать и пересылать патчи" или там отфутболивать к руководству по гит. 
(Нет, это в любом случае буду не я, не имею больше времени на бесплатные :) и к тому же непроизводительные действия. Но вдруг найдётся ещё какой-нибудь идеалист.)

**Comment by alexferman** [comment]
"On a separate issue, meanwhile, Stallman questioned his quoted use of
the word ``fucking.'' Again, I didn't have the moment on tape, but I
wrote back that I distinctly recalled an impressive display of
profanity, a reminder of Richard's New York roots, and was willing to
stand by that memory.

An email response from Richard, received the next day, restated the
critique in a way that forced me to go back and re-read the first
message. "

Как видно, наличие спора прослеживается и в оригинале.

Впрочем, если ваша позиция сводится к "ворвусь в обсуждение и объявлю что ваш перевод херня, и задумка ваша - бред, игнорируя все аргументы", то лучше не тратьте своё драгоценное время на "бредовую задумку", мы уж сами как-нибудь.
