### ISSUE TITLE
название книги, ещё раз

### ISSUE THREAD

**Issue by yurytch** [jollheef/free-as-in-freedom-v2-ru#32]
Коллеги, ещё раз внимательно посмотрите на название. Вместо названия книги-биографии получилось чёрт знает что -- и не название, и не книги, и не биографии. В книге речь о программах, и только о них, а актуальная форма названия это просто кирпич.

Умоляю, по крайней мере уберите "освобождение компьютера", это мимо цели совершенно. Даже если это вымучили от Столлмана.

**Comment by jollheef** [comment]
Дубль #11

**Comment by yurytch** [comment]
11 ссылается на 32, а 32 на 11. Что ж, как знаете. Перевод плохонький, начиная вот прямо с названия. Если каждую очевидную вещь вот так пробивать, не хватит ни сил, ни времени. Пока!

**Comment by jollheef** [comment]
Добрый день. 

Не стоит называть перевод «плохеньким» только по той причине, что ваши правки не принимаются без обсуждения.

**Comment by yurytch** [comment]
> Не стоит называть перевод «плохеньким» только по той причине, что ваши правки не принимаются без обсуждения.

Друзья, перевод не потому "такой", что "правки не принимаются" (впрочем, техпроцесс для них мог бы быть и попроще - вот я не владею гитхабом как следует, мне не очень понятно, как работать, а трудоёмкость изготовления патчей по одному - высоковата), а потому, что такие правки вообще оказались нужны. Вы же видели, о чём речь в #29 и #30?
Ну без обид - то ли по-английски толком не прочтено, то ли по-русски написано "вполглаза". Мне такая ситуация непонятна.

**Comment by jollheef** [comment]
> впрочем, техпроцесс для них мог бы быть и попроще - вот я не владею гитхабом как следует, мне не очень понятно, как работать, а трудоёмкость изготовления патчей по одному - высоковата

GitHub владеть не обязательно (более того ― этот репозиторий существует только для того, чтобы у тех, кто уже пользуется GitHub ― была возможность отправить правки так, как ему удобно), можно также использовать (и более желательно, на самом деле, потому что любая завязка на GitHub это скорее отрицательный момент, чем положительный) git-send-email на `patch@dumpstack.io`.

Но знание Git необходимо, потому что иначе работать с множеством правок было бы просто невозможно.

> перевод не потому "такой", что "правки не принимаются", а потому, что такие правки вообще оказались нужны. 

Это нормальный процесс. Достичь идеала возможно только последовательнымми итерациями с множеством глаз, которые будут замечать ошибки.

**Comment by yurytch** [comment]
> Но знание Git необходимо, потому что иначе работать с множеством правок было бы просто невозможно.
Объясните, пожалуйста, как, и можно ли, реализовать "на чистом гит" или через гитхаб такой технологический процесс:
- дерево копируется ("клонируется"?) к себе
- файлы глав читаются и правятся по одному
- эти правки автоматически разбиваются на части и отправляются (или можно дать правку на главу сразу?)
Нужен алгоритм действий, хотя бы в не слишком общих чертах.

**Comment by jollheef** [comment]
1. [Документация git](https://git-scm.com/doc).
2. [Pull request](https://www.atlassian.com/git/tutorials/making-a-pull-request).
3. [git-send-email](https://git-scm.com/docs/git-send-email).

**Comment by yurytch** [comment]
thanks for nothing
