### ISSUE TITLE
перевод пассажа про gosmacs в главе 9

### ISSUE THREAD

**Issue by sash-kan** [jollheef/free-as-in-freedom-v2-ru#33]
оригинал: "Making Gosmacs nonfree was unethical according to the ethical ideas of the free software movement, because (as proprietary software) it did not respect its users' freedom, but this issue had nothing to do with where the ideas in Gosmacs came from."

перевод: "Делать же Gosmacs несвободным совершенно неприемлемо, потому что тогда
о свободе пользователей не могло быть и речи."

по-моему, смысл, изложенный в оригинале, совсем потерялся. правда, затрудняюсь предложить свой вариант (ввиду некоторой накрученности формулировки).

**Comment by sash-kan** [comment]
судя по всему, речь о том, что gosmacs в один прекрасный момент **стал** проприетарным. и вот это самое изменение и называется неэтичным.
но вот что именно подразумевается здесь под "this issue" — непонятно. факт преобразования gosemacs в проприетарщину?

**Comment by yurytch** [comment]
> судя по всему, речь о том, что gosmacs в один прекрасный момент **стал** проприетарным. и вот это самое изменение и называется неэтичным.
> но вот что именно подразумевается здесь под "this issue" — непонятно. факт преобразования gosemacs в проприетарщину?

Да, в цитируемом вами смысл потерян.
Автор имел в виду, что проблема свободы ("свободности") данного приложения не имела ничего общего с тем, какие здесь были реализованы (технические) идеи.

**Comment by alexferman** [comment]
Пофиксил, вроде смысл теперь передан верно.

**Comment by jollheef** [comment]
Исправлено в #35
