### ISSUE TITLE
Гномы в 3 главе

### ISSUE THREAD

**Issue by ikorolev93** [jollheef/free-as-in-freedom-v2-ru#6]
Оригинал:
>The image dwarfs accompanying photos of Lippman's nieces and nephews[...]

Перевод:
>Фото племянниц и племянников Липпман перемежаются картинками гномов

dwarfs - здесь же глагол? По смыслу the image (из предыдущего предложения - фото Столлмана 8x10) доминирует над остальными фотографиями.
https://en.wiktionary.org/wiki/dwarf#Verb - второе и третье значения подходят.

**Comment by jollheef** [comment]
Привет,

Спасибо за правку.

@alexferman, у тебя какие мысли?

**Comment by alexferman** [comment]
Всё верно, это глагол - фото Ричарда доминирует над фотографиями племянниц и племянников. Там надо весь абзац поправить, завтра сделаю.

**Comment by jollheef** [comment]
fixed in #9
